name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # You can use v3 or another version as needed.

      - name: Setup Node.js environment
        uses: actions/setup-node@v4  # Use the appropriate version.
        with:
          node-version: 12.x  # Set the Node.js version you need.

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0  # Use the appropriate version.
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHOPEASE_ANGULAR16 }}
          channelId: live
          projectId: shopease-angular16
